name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Print pwd
        run: pwd

      - name: List files
        run: ls -la

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        working-directory: .

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        working-directory: .

      - name: Run tests
        run: ./gradlew test
        working-directory: .

  sonarcloud_analysis:
    needs: ["build", "test"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        working-directory: .

      - name: SonarCloud analysis
        run: ./gradlew build jacocoTestReport sonarqube --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: .

  check_docker_availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker availability
        run: |
          docker --version

  build_docker_images:
    needs: ["build", "test", "check_docker_availability"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: docker/setup-buildx-action@v2

      - name: Print pwd
        run: pwd

      - name: List files
        run: ls ../ -la

      - name: Build Docker Images
        run: docker-compose build
        working-directory: .