name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

  sonarcloud_analysis:
    needs: ["build", "test"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      # Configura JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Concede permisos de ejecución a gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Ejecuta el análisis de SonarCloud
      - name: SonarCloud analysis
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  check_docker_availability:
    needs: [ "build", "test", "sonarcloud_analysis" ]
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - # create a build kit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - # build the container image and push it to Docker \
        # Hub with the name clockbox.
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $/clockbox:latest